/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { OffreFret, OffreStatus, MoyenType, MoyenTransport, UserProfile, ProfileType, PropositionPrix, Facture, FactureStatus } from "./types";

export const MOCK_USERS: UserProfile[] = [
  {
    id: "user-admin",
    nom: "NETLOG",
    prenom: "Admin",
    raisonSociale: "NETLOG Administration",
    nrc: "00/00-0000000 B 00",
    adresse: "Alger, Algérie",
    email: "admin@netlog.dz",
    tel: "021 00 00 00",
    profil: ProfileType.Admin,
    password: "Admin@2025",
    status: "valide"
  },
  {
    id: "user-do-1",
    nom: "Babassi",
    prenom: "Kamel",
    raisonSociale: "SARL BATIMEX",
    nrc: "16/00-0987654 B 20",
    adresse: "05 Avenue de l'ALN, Alger",
    email: "do@batimex.dz",
    tel: "+213 21 44 55 66",
    profil: ProfileType.DonneurOrdre,
    password: "Test@2025",
    status: "valide",
    wilaya: "Alger",
    typeEntite: "Entreprise",
    secteur: "Commerce",
    volumeFret: "5-20 camions"
  },
  {
    id: "user-trans-1",
    nom: "Benzekri",
    prenom: "Ahmed",
    raisonSociale: "Transports Benzekri",
    nrc: "16/00-1122334 B 20",
    adresse: "Zone Industrielle Rouïba, Alger",
    email: "ahmed@transport.dz",
    tel: "0555 12 34 56",
    profil: ProfileType.Transporteur,
    password: "Test@2025",
    status: "valide",
    wilaya: "Alger",
    typeEntite: "Entreprise de transport",
    nbCamions: "6-20",
    wilayaActivite: "Alger"
  },
  {
    id: "user-comm-1",
    nom: "Ouali",
    prenom: "Farid",
    raisonSociale: "Farid Ouali BVF",
    nrc: "31/00-3344556 B 20",
    adresse: "Centre ville, Oran",
    email: "farid@commercial.dz",
    tel: "0661 77 88 99",
    profil: ProfileType.Commercial,
    password: "Test@2025",
    status: "valide",
    wilaya: "Oran",
    diplome: "Licence",
    experienceTransport: "Oui",
    wilayaIntervention: "Oran"
  },
  {
    id: "user-en-attente-1",
    nom: "Messaoudi",
    prenom: "Salim",
    raisonSociale: "EURL Transit Plus",
    nrc: "16/00-9988776 A 20",
    adresse: "Dar El Beïda, Alger",
    email: "new@test.dz",
    tel: "0770 11 22 33",
    profil: ProfileType.DonneurOrdre,
    password: "Test@2025",
    status: "en_attente",
    wilaya: "Alger",
    typeEntite: "Entreprise",
    secteur: "Agroalimentaire",
    volumeFret: "< 5 camions"
  },
  {
    id: "user-driver-1",
    nom: "Mahmoudi",
    prenom: "Mohamed",
    raisonSociale: "Chauffeur Benzekri Transports",
    nrc: "N/A",
    adresse: "Bab Ezzouar, Alger",
    email: "mohamed@chauffeur.dz",
    tel: "0666 44 55 66",
    profil: ProfileType.Chauffeur,
    password: "Test@2025",
    status: "valide",
    transporteurParentId: "user-trans-1",
    disponibiliteChauffeur: "Disponible",
    positionChauffeur: "Alger"
  }
];

export const MOCK_MOYENS: MoyenTransport[] = [
  {
    id: "moyen-1",
    transporteurId: "user-trans-1",
    type: MoyenType.Tautliner,
    marque: "Renault Trucks T480",
    immatriculation: "00123-120-16",
    poidsUtileMax: 24, // tonnes
    longueurMax: 13.6, // m
  },
  {
    id: "moyen-2",
    transporteurId: "user-trans-1",
    type: MoyenType.Plateau,
    marque: "Volvo FH16",
    immatriculation: "09876-118-31",
    poidsUtileMax: 45, // tonnes
    longueurMax: 14.0, // m
  },
  {
    id: "moyen-3",
    transporteurId: "user-trans-1",
    type: MoyenType.Citerne,
    marque: "Scania R500",
    immatriculation: "07543-115-30",
    poidsUtileMax: 32, // tonnes
    longueurMax: 12.0, // m
  }
];

export const MOCK_OFFRES: OffreFret[] = [
  {
    id: "offre-1",
    donneurId: "user-do-1",
    donneurRaisonSociale: "SARL BATIMEX",
    depart: "Alger",
    arrivee: "Sétif",
    departDetails: "Wilaya d'Alger, Port d'Alger",
    arriveeDetails: "Wilaya de Sétif, Zone Industrielle",
    dateChargement: "2026-06-01",
    dateLivraison: "2026-06-03",
    poids: 30,
    longueurExigee: 13.6,
    marchandise: "Ciment",
    moyenExige: MoyenType.Tautliner,
    nombreVoyages: 1,
    prixFixe: 85000,
    commentaire: "Transport de ciment en sacs sur palettes.",
    status: OffreStatus.Publie,
    codeConfirmation: "8820",
    dateCreation: "2026-05-25T08:00:00Z"
  },
  {
    id: "offre-2",
    donneurId: "user-do-2",
    donneurRaisonSociale: "SPA ALGERIA FOOD",
    depart: "Oran",
    arrivee: "Adrar",
    departDetails: "Wilaya d'Oran, Zone d'activités",
    arriveeDetails: "Wilaya d'Adrar, Centre ville",
    dateChargement: "2026-06-02",
    dateLivraison: "2026-06-05",
    poids: 20,
    longueurExigee: 12.0,
    marchandise: "Denrées alimentaires",
    moyenExige: MoyenType.CamionFrigorifique,
    nombreVoyages: 1,
    commentaire: "Produits laitiers et boissons au frais.",
    status: OffreStatus.Publie,
    codeConfirmation: "1099",
    dateCreation: "2026-05-25T08:05:00Z"
  },
  {
    id: "offre-3",
    donneurId: "user-do-1",
    donneurRaisonSociale: "SARL BATIMEX",
    depart: "Béjaïa",
    arrivee: "Alger",
    departDetails: "Port de Béjaïa, Quai de chargement",
    arriveeDetails: "Wilaya d'Alger, Centre de Distribution",
    dateChargement: "2026-06-03",
    dateLivraison: "2026-06-04",
    poids: 22,
    longueurExigee: 13.6,
    marchandise: "Conteneur 40 pieds",
    moyenExige: MoyenType.PorteEngin,
    nombreVoyages: 3,
    prixFixe: 45000,
    commentaire: "Châssis porte-conteneur exigé.",
    status: OffreStatus.Publie,
    codeConfirmation: "3015",
    dateCreation: "2026-05-25T08:10:00Z"
  },
  {
    id: "offre-4",
    donneurId: "user-do-3",
    donneurRaisonSociale: "BTP EST CONSTRUCTIONS",
    depart: "Blida",
    arrivee: "Constantine",
    departDetails: "Wilaya de Blida, Carrière d'agrégats",
    arriveeDetails: "Wilaya de Constantine, Chantier de construction",
    dateChargement: "2026-06-04",
    dateLivraison: "2026-06-05",
    poids: 40,
    longueurExigee: 10.0,
    marchandise: "Matériaux BTP (sable, gravier)",
    moyenExige: MoyenType.BenneBasculante,
    nombreVoyages: 5,
    prixFixe: 70000,
    commentaire: "Camion benne obligatoire.",
    status: OffreStatus.Publie,
    codeConfirmation: "4509",
    dateCreation: "2026-05-25T08:15:00Z"
  },
  {
    id: "offre-5",
    donneurId: "user-do-4",
    donneurRaisonSociale: "SIDER EL HADJAR SPA",
    depart: "Annaba",
    arrivee: "Alger",
    departDetails: "Complexe Sidérurgique El Hadjar, Annaba",
    arriveeDetails: "Dépôt d'Alger, Rouïba",
    dateChargement: "2026-06-05",
    dateLivraison: "2026-06-07",
    poids: 25,
    longueurExigee: 13.6,
    marchandise: "Produits métallurgiques",
    moyenExige: MoyenType.Plateau,
    nombreVoyages: 2,
    prixFixe: 95000,
    commentaire: "Tubes d'acier longs de 12 mètres.",
    status: OffreStatus.Publie,
    codeConfirmation: "5201",
    dateCreation: "2026-05-25T08:20:00Z"
  },
  {
    id: "offre-6",
    donneurId: "user-do-5",
    donneurRaisonSociale: "SPA CEVITAL AGRO",
    depart: "Tlemcen",
    arrivee: "Oran",
    departDetails: "Dépôt Régional de Tlemcen",
    arriveeDetails: "Port d'Oran",
    dateChargement: "2026-06-06",
    dateLivraison: "2026-06-07",
    poids: 15,
    longueurExigee: 12.0,
    marchandise: "Huile de table",
    moyenExige: MoyenType.Fourgon,
    nombreVoyages: 4,
    prixFixe: 30000,
    commentaire: "Bouteilles d'huile emballées sous film étirable.",
    status: OffreStatus.Publie,
    codeConfirmation: "6102",
    dateCreation: "2026-05-25T08:25:00Z"
  },
  {
    id: "offre-7",
    donneurId: "user-do-6",
    donneurRaisonSociale: "SARL ENIE ELECTRONIQUE",
    depart: "Constantine",
    arrivee: "Ghardaïa",
    departDetails: "Dépôt ENIE Constantine",
    arriveeDetails: "Point de vente ENIE Ghardaïa",
    dateChargement: "2026-06-07",
    dateLivraison: "2026-06-09",
    poids: 10,
    longueurExigee: 10.0,
    marchandise: "Matériaux électriques",
    moyenExige: MoyenType.Fourgon,
    nombreVoyages: 1,
    prixFixe: 120000,
    commentaire: "Appareils sensibles sous carton.",
    status: OffreStatus.Publie,
    codeConfirmation: "7044",
    dateCreation: "2026-05-25T08:30:00Z"
  },
  {
    id: "offre-8",
    donneurId: "user-do-7",
    donneurRaisonSociale: "ENTREPRISE DE FORAGE ENFOR",
    depart: "Alger",
    arrivee: "Ouargla",
    departDetails: "Port sec de Rouïba, Alger",
    arriveeDetails: "Chantier pétrolier Hassi Messaoud, Ouargla",
    dateChargement: "2026-06-08",
    dateLivraison: "2026-06-11",
    poids: 5,
    longueurExigee: 13.6,
    marchandise: "Équipements industriels",
    moyenExige: MoyenType.Plateau,
    nombreVoyages: 1,
    prixFixe: 180000,
    commentaire: "Pièces de rechange pour derrick de forage.",
    status: OffreStatus.Publie,
    codeConfirmation: "8522",
    dateCreation: "2026-05-25T08:35:00Z"
  },
  {
    id: "offre-9",
    donneurId: "user-do-8",
    donneurRaisonSociale: "EURL L'ALGERIENNE DES LAITS",
    depart: "Sétif",
    arrivee: "Béjaïa",
    departDetails: "Laiterie de Sétif",
    arriveeDetails: "Dépôt Bejaia centre",
    dateChargement: "2026-06-09",
    dateLivraison: "2026-06-10",
    poids: 8,
    longueurExigee: 8.0,
    marchandise: "Lait et produits laitiers",
    moyenExige: MoyenType.CamionFrigorifique,
    nombreVoyages: 3,
    prixFixe: 25000,
    commentaire: "Maintien de la chaîne du froid à 4°C obligatoire.",
    status: OffreStatus.Publie,
    codeConfirmation: "9001",
    dateCreation: "2026-05-25T08:40:00Z"
  },
  {
    id: "offre-10",
    donneurId: "user-do-9",
    donneurRaisonSociale: "AGRO-ALGERIE ORANGES",
    depart: "Médéa",
    arrivee: "Alger",
    departDetails: "Verger de Médéa",
    arriveeDetails: "Marché de gros des Eucalyptus, Alger",
    dateChargement: "2026-06-10",
    dateLivraison: "2026-06-11",
    poids: 20,
    longueurExigee: 13.6,
    marchandise: "Agrumes (oranges)",
    moyenExige: MoyenType.Tautliner,
    nombreVoyages: 2,
    prixFixe: 40000,
    commentaire: "Orange de saison en caissettes bois.",
    status: OffreStatus.Publie,
    codeConfirmation: "1055",
    dateCreation: "2026-05-25T08:45:00Z"
  }
];

export const MOCK_PROPOSITIONS: PropositionPrix[] = [
  {
    id: "prop-1",
    offreId: "offre-1",
    transporteurId: "user-trans-1",
    transporteurRaisonSociale: "Trans-Sud Logistics Dz",
    moyenId: "moyen-1",
    prixPropose: 175000,
    commentaire: "Camion disponible immédiatement, chauffeur expérimenté.",
    status: "En attente"
  }
];

export const MOCK_FACTURES: Facture[] = [];
